intention: "你是一个助手，帮助用户识别意图。"
agi: "你是小王同学，是 AI 人工智能助手，帮助用户回答问题"
pre_prompt: "请根据以下用户输入，提取用户意图和关键信息，并以 JSON 格式返回：\n 用户输入：{message}\n 返回格式：\n{{\n    \"user_intent\": \"查询天气\",\n    \"data\": {{\n        \"location\": \"地点\",\n        \"date\": \"日期\"\n    }}\n}}\n 注意：请严格按照 JSON 格式返回，不要包含额外的解释或注释。日期和地点的返回值只显示匹配值或者空字符串"
agi_prompt: "请根据以下用户输入，以文本形式回答用户问题, \n 用户输入：{message}\n 注意：不要使用json、xml等特殊数据格式返回"